In [52]:
import selenium                               
from selenium import webdriver                
import pandas as pd                           
from selenium.webdriver.common.by import By   
import warnings                               
warnings.filterwarnings("ignore")
import time 
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import requests

# Question 1)

In [2]:
driver = webdriver.Chrome()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [3]:
driver.maximize_window()

In [12]:
rank = []
name = []
artist = []
upload_date = []
views =[]

In [13]:
rank_tag = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[1]')
for r in rank_tag:
    rank.append(r.text)
    
name_tag = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[2]')
for n in name_tag:
    name.append(n.text)
name = [item.split('[')[0].strip() for item in name]
    
    
artist_tag = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[3]')
for a in artist_tag:
    artist.append(a.text)
    
ud = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[5]')
for u in ud:
    upload_date.append(u.text)
    
vw = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[4]')
for v in vw:
    views.append(v.text)

In [15]:
print(len(rank),len(name),len(artist),len(upload_date),len(views))

30 30 30 30 30

In [16]:
df = pd.DataFrame({'RANK':rank,'NAME OF VIDEO':name,'ARTIST':artist,'VIEWS (IN BILLION)':views,'UPLOADED ON':upload_date})
df

,RANK,NAME OF VIDEO,ARTIST,VIEWS (IN BILLION),UPLOADED ON
0,1.,"""Baby Shark Dance""",Pinkfong Baby Shark - children's songs,13.18,"June 17, 2016"
1,2.,"""Despacito""",Luis Fonsi,8.23,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""",LooLoo Kids - nursery rhymes,6.76,"October 8, 2016"
3,4.,"""Bath Song""",Cocomelon - nursery rhymes,6.33,"May 2, 2018"
4,5.,"""Shape of You""",Ed Sheeran,6.05,"January 30, 2017"
5,6.,"""See You Again""",Wiz Khalifa,5.98,"April 6, 2015"
6,8.,"""Wheels on the Bus""",Cocomelon - nursery rhymes,5.46,"May 24, 2018"
7,7.,"""Phonics Song with Two Words""",ChuChu TV - children's songs,5.42,"March 6, 2014"
8,9.,"""Uptown Funk""",Mark Ronson,4.99,"November 19, 2014"
9,10.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV - children's songs,4.94,"February 27, 2018"
10,11.,"""Gangnam Style""",Psy,4.86,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""",Get Movies - children's songs,4.55,"January 31, 2012"
12,13.,"""Dame Tu Cosita""",El Chombo,4.41,"April 5, 2018"
13,14.,"""Axel F""",Crazy Frog,4.00,"June 16, 2009"
14,15.,"""Sugar""",Maroon 5,3.91,"January 14, 2015"
15,16.,"""Roar""",Katy Perry,3.84,"September 5, 2013"
16,17.,"""Counting Stars""",OneRepublic,3.84,"May 31, 2013"
17,18.,"""Baa Baa Black Sheep""",Cocomelon - nursery rhymes,3.73,"June 25, 2018"
18,19.,"""Sorry""",Justin Bieber,3.69,"October 22, 2015"
19,20.,"""Waka Waka (This Time for Africa)""",Shakira,3.68,"June 4, 2010"
20,21.,"""Thinking Out Loud""",Ed Sheeran,3.63,"October 7, 2014"
21,22.,"""Lakdi Ki Kathi""",Jingle Toons,3.63,"June 14, 2018"
22,23.,"""Dark Horse""",Katy Perry,3.56,"February 20, 2014"
23,24.,"""Perfect""",Ed Sheeran,3.51,"November 9, 2017"
24,25.,"""Faded""",Alan Walker,3.49,"December 3, 2015"
25,26.,"""Let Her Go""",Passenger,3.48,"July 25, 2012"
26,27.,"""Humpty the train on a fruits ride""",Kiddiestv Hindi - children's songs,3.51,"January 26, 2018"
27,28.,"""Girls Like You""",Maroon 5,3.45,"May 31, 2018"
28,29.,"""Bailando""",Enrique Iglesias,3.43,"April 11, 2014"
29,30.,"""Lean On""",Major Lazer,3.43,"March 22, 2015"

# Question 2)

In [2]:
driver = webdriver.Chrome()
driver.get("http://www.bcci.tv/")

In [3]:
driver.maximize_window()

In [4]:
menu = driver.find_element(By.XPATH,'/html/body/nav/div[1]/button')
menu.click()

In [7]:
international = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
international.click()

In [23]:
title = []
series =[]
place =[]
date = []
time = []

In [9]:
for i in range(10):
    
    try:    
        show_more_button = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div/button')
        show_more_button.click()
        
    except NoSuchElementException:
        break

In [24]:
Title = driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[3]/div/span[1]')
for t in Title:
    title.append(t.text)
for i in range(len(title)):
    title[i] = title[i].replace('-', '')
    
Series = driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/h5')
for s in Series:
    series.append(s.text)
    
Date = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for d in Date:
    date.append(d.text)
    
Time = driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for t in Time:
    time.append(t.text)
    
Place = driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[3]/div/span[2]')
for p in Place:
    place.append(p.text)

In [26]:
df = pd.DataFrame({'Match Title':title,'Series':series,'Place':place,'Date':date,'Time':time})
df

,Match Title,Series,Place,Date,Time
0,1st T20I,INDIA TOUR OF IRELAND 2023,"The Village,",18 AUG 2023,7:30 PM IST
1,2nd T20I,INDIA TOUR OF IRELAND 2023,"The Village,",20 AUG 2023,7:30 PM IST
2,3rd T20I,INDIA TOUR OF IRELAND 2023,"The Village,",23 AUG 2023,7:30 PM IST
3,1st ODI,ASIA CUP 2023,"Pallekele International Cricket Stadium,",2 SEP 2023,10:00 AM IST
4,2nd ODI,ASIA CUP 2023,"Pallekele International Cricket Stadium,",4 SEP 2023,10:00 AM IST
5,1st ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,",22 SEP 2023,1:30 PM IST
6,2nd ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Holkar Cricket Stadium,",24 SEP 2023,1:30 PM IST
7,3rd ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium,",27 SEP 2023,1:30 PM IST
8,1st ODI,ICC MENS WORLD CUP 2023,"MA Chidambaram Stadium,",8 OCT 2023,2:00 PM IST
9,2nd ODI,ICC MENS WORLD CUP 2023,"Arun Jaitley Stadium,",11 OCT 2023,2:00 PM IST
10,3rd ODI,ICC MENS WORLD CUP 2023,"Narendra Modi Stadium,",14 OCT 2023,2:00 PM IST
11,4th ODI,ICC MENS WORLD CUP 2023,"Maharashtra Cricket Association Stadium,",19 OCT 2023,2:00 PM IST
12,5th ODI,ICC MENS WORLD CUP 2023,"Himachal Pradesh Cricket Association Stadium,",22 OCT 2023,2:00 PM IST
13,6th ODI,ICC MENS WORLD CUP 2023,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29 OCT 2023,2:00 PM IST
14,7th ODI,ICC MENS WORLD CUP 2023,"Wankhede Stadium,",2 NOV 2023,2:00 PM IST
15,8th ODI,ICC MENS WORLD CUP 2023,"Eden Gardens,",5 NOV 2023,2:00 PM IST
16,9th ODI,ICC MENS WORLD CUP 2023,"M Chinnaswamy Stadium,",12 NOV 2023,2:00 PM IST
17,1st T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",23 NOV 2023,7:00 PM IST
18,2nd T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Greenfield International Stadium,",26 NOV 2023,7:00 PM IST
19,3rd T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Barsapara Cricket Stadium,",28 NOV 2023,7:00 PM IST
20,4th T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Vidarbha Cricket Association Stadium,",1 DEC 2023,7:00 PM IST
21,5th T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Rajiv Gandhi International Stadium,",3 DEC 2023,7:00 PM IST
22,1st T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"Kingsmead,",10 DEC 2023,9:30 PM IST
23,2nd T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"St George's Park,",12 DEC 2023,9:30 PM IST
24,3rd T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"The Wanderers Stadium,",14 DEC 2023,9:30 PM IST
25,1st ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,Johannesburg,17 DEC 2023,2:00 PM IST
26,2nd ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,"St George's Park,",19 DEC 2023,2:00 PM IST
27,3rd ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,"Boland Park,",21 DEC 2023,2:00 PM IST
28,1st Test,INDIA TOUR OF SOUTH AFRICA 2023-24,"SuperSport Park,",26 DEC 2023,1:30 PM IST
29,2nd Test,INDIA TOUR OF SOUTH AFRICA 2023-24,"Newlands,",3 JAN 2024,1:30 PM IST
30,1st T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,",11 JAN 2024,7:00 PM IST
31,2nd T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"Holkar Cricket Stadium,",14 JAN 2024,7:00 PM IST
32,3rd T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"M Chinnaswamy Stadium,",17 JAN 2024,7:00 PM IST
33,1st Test,ENGLAND TOUR OF INDIA 2023-24,"Rajiv Gandhi International Stadium,",25 JAN 2024,9:30 AM IST
34,2nd Test,ENGLAND TOUR OF INDIA 2023-24,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",2 FEB 2024,9:30 AM IST
35,3rd Test,ENGLAND TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium,",15 FEB 2024,9:30 AM IST
36,4th Test,ENGLAND TOUR OF INDIA 2023-24,"JSCA International Stadium Complex,",23 FEB 2024,9:30 AM IST
37,5th Test,ENGLAND TOUR OF INDIA 2023-24,"Himachal Pradesh Cricket Association Stadium,",7 MAR 2024,9:30 AM IST

# Question 3)

In [27]:
driver = webdriver.Chrome()
driver.get("http://statisticstimes.com/")

In [28]:
driver.maximize_window()

In [31]:
economy = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()

In [32]:
india = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()

In [33]:
gdp = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
gdp.click()

In [38]:
rank = []
state = []
gsdp_18_19 = []
gsdp_19_20 = []
share_18_19 = []
gdp = []

In [39]:
Rank = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[1]')
for r in Rank:
    rank.append(r.text)
    
State = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[2]')
for s in State:
    state.append(s.text)
    
G18 = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[4]')
for g in G18:
    gsdp_18_19.append(g.text)
    
G19 = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[3]')
for g in G19:
    gsdp_19_20.append(g.text)
    
Share = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[5]')
for s in Share:
    share_18_19.append(s.text)
    
GDP = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[6]')
for g in GDP:
    gdp.append(g.text)

In [40]:
print(len(rank),len(state),len(gsdp_18_19),len(gsdp_19_20),len(share_18_19),len(gdp))

33 33 33 33 33 33

In [41]:
df = pd.DataFrame({'Rank':rank,'State':state,'GSDP(18-19)':gsdp_18_19,'GSDP(19-20)':gsdp_19_20,'Share(18-19)':share_18_19,'GDP($ billion)':gdp})
df

,Rank,State,GSDP(18-19),GSDP(19-20),Share(18-19),GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Question 4)

In [23]:
driver = webdriver.Chrome()
driver.get("https://github.com/")

In [24]:
driver.maximize_window()

In [25]:
menu = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/button/span')
menu.click()

In [26]:
open_source = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
open_source.click()

In [27]:
trending = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [28]:
title = [] 
desc = [] 
cont_count = []
language = []
URL = []

In [30]:
Title = driver.find_elements(By.XPATH,'/html/body/div[1]/div[4]/main/div[3]/div/div[2]/article/h2/a')
for t in Title:
    title.append(t.text)
    
Language = driver.find_elements(By.XPATH,'/html/body/div[1]/div[4]/main/div[3]/div/div[2]/article/div[2]/span[1]')
for l in Language:
    language.append(l.text)
for i in range(len(language)):
    language[i] = language[i].replace('Built by', '-')
    
url = driver.find_elements(By.XPATH,'//a[@class="Link"]')
for u in url:
    URL.append(u.get_attribute('href'))

In [31]:
URL

['https://github.com/joonspk-research/generative_agents',
 'https://github.com/modelscope/facechain',
 'https://github.com/phoboslab/wipeout-rewrite',
 'https://github.com/clockworklabs/SpacetimeDB',
 'https://github.com/yt-dlp/yt-dlp',
 'https://github.com/id-Software/quake2-rerelease-dll',
 'https://github.com/huggingface/candle',
 'https://github.com/TheAlgorithms/Python',
 'https://github.com/bitcoin/bitcoin',
 'https://github.com/Plachtaa/VITS-fast-fine-tuning',
 'https://github.com/graphdeco-inria/gaussian-splatting',
 'https://github.com/FlowiseAI/Flowise',
 'https://github.com/binhnguyennus/awesome-scalability',
 'https://github.com/PeiQi0/PeiQi-WIKI-Book',
 'https://github.com/DeBankDeFi/DeBankChain',
 'https://github.com/taikoxyz/taiko-mono',
 'https://github.com/521xueweihan/HelloGitHub',
 'https://github.com/homanp/superagent',
 'https://github.com/PaperMC/Folia',
 'https://github.com/ytdl-org/youtube-dl',
 'https://github.com/YBIFoundation/Fundamental',
 'https://github.com/libsdl-org/SDL',
 'https://github.com/Infisical/infisical',
 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
 'https://github.com/MustardChef/WSABuilds']

In [32]:
for u in URL:
    driver.get(u)
    time.sleep(15)

    try:
        C = driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[6]/div/h2/a/span')
        cont_count.append(C.text)
    except NoSuchElementException:
        cont_count.append('-')
        
    try:
        D = driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/p')
        desc.append(D.text)
    except NoSuchElementException:
        desc.append('-')

In [34]:
df = pd.DataFrame({'Repository title':title,'Repository description':desc,'Contributors count':cont_count,'Language used':language})
df

,Repository title,Repository description,Contributors count,Language used
0,joonspk-research / generative_agents,Generative Agents: Interactive Simulacra of Hu...,-,-
1,modelscope / facechain,FaceChain is a deep-learning toolchain for gen...,-,Python
2,phoboslab / wipeout-rewrite,-,-,C
3,clockworklabs / SpacetimeDB,Multiplayer at the speed of light,-,Rust
4,yt-dlp / yt-dlp,A youtube-dl fork with additional features and...,-,Python
5,id-Software / quake2-rerelease-dll,-,-,C
6,huggingface / candle,Minimalist ML framework for Rust,-,Rust
7,TheAlgorithms / Python,All Algorithms implemented in Python,987,Python
8,bitcoin / bitcoin,Bitcoin Core integration/staging tree,-,C++
9,Plachtaa / VITS-fast-fine-tuning,This repo is a pipeline of VITS finetuning for...,-,Python
10,graphdeco-inria / gaussian-splatting,"Original reference implementation of ""3D Gauss...",-,Python
11,FlowiseAI / Flowise,Drag & drop UI to build your customized LLM flow,-,TypeScript
12,binhnguyennus / awesome-scalability,"The Patterns of Scalable, Reliable, and Perfor...",21,-
13,PeiQi0 / PeiQi-WIKI-Book,面向网络安全从业者的知识文库🍃,-,-
14,DeBankDeFi / DeBankChain,-,-,Go
15,taikoxyz / taiko-mono,"A decentralized, Ethereum-equivalent ZK-Rollup. 🥁",-,HTML
16,521xueweihan / HelloGitHub,"分享 GitHub 上有趣、入门级的开源项目。Share interesting, entr...",-,Python
17,homanp / superagent,"🥷 Superagent - Build, deploy, and manage LLM-p...",-,JavaScript
18,PaperMC / Folia,Fork of Paper which adds regionised multithrea...,19,Kotlin
19,ytdl-org / youtube-dl,Command-line program to download videos from Y...,-,Python
20,YBIFoundation / Fundamental,Jupyter Notebook,-,Jupyter Notebook
21,libsdl-org / SDL,Simple Directmedia Layer,-,C
22,Infisical / infisical,"♾ Infisical is an open-source, end-to-end encr...",-,TypeScript
23,AUTOMATIC1111 / stable-diffusion-webui,Stable Diffusion web UI,-,Python
24,MustardChef / WSABuilds,Run Windows Subsystem For Android on your Wind...,-,Shell

# Question 5)

In [3]:
driver = webdriver.Chrome()
driver.get("https://www.billboard.com/")

In [5]:
driver.maximize_window()

In [6]:
menu_button = driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button')
menu_button.click()

In [7]:
charts = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/h3/a')
charts.click()

In [8]:
b100 = driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a')
b100.click()

In [9]:
song = []
artist = []
lw_rank = []
p_rank = []
weeks = []

In [10]:
Song = driver.find_elements(By.XPATH,'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div/ul/li[4]/ul/li[1]/h3')
for s in Song:
    song.append(s.text)
    
Artist = driver.find_elements(By.XPATH,'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div/ul/li[4]/ul/li[1]/span')
for a in Artist:
    artist.append(a.text)
    
lw = driver.find_elements(By.XPATH,'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div/ul/li[4]/ul/li[4]')
for l in lw:
    lw_rank.append(l.text)
    
p = driver.find_elements(By.XPATH,'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div/ul/li[4]/ul/li[5]')
for P in p:
    p_rank.append(P.text)
    
    
Weeks = driver.find_elements(By.XPATH,'//*[@id="post-1479786"]/div[3]/div/div/div/div[2]/div/ul/li[4]/ul/li[6]')
for w in Weeks:
    weeks.append(w.text)

In [11]:
print(len(song),len(artist),len(p_rank),len(lw_rank),len(weeks))

100 100 100 100 100

In [12]:
df = pd.DataFrame({'Song name':song,'Artist Name':artist,'Last week Rank':lw_rank,'Peak Rank':p_rank,'Weeks on board':weeks})
df

,Song name,Artist Name,Last week Rank,Peak Rank,Weeks on board
0,Last Night,Morgan Wallen,1,1,28
1,Fast Car,Luke Combs,2,2,20
2,Cruel Summer,Taylor Swift,4,3,14
3,Calm Down,Rema & Selena Gomez,6,3,49
4,Fukumean,Gunna,7,4,8
...,...,...,...,...,...
95,Lagunas,Peso Pluma & Jasiel Nunez,-,77,6
96,Overdrive,Post Malone,68,47,3
97,"Bzrp Music Sessions, Vol. 55",Bizarrap & Peso Pluma,99,31,10
98,Dawns,Zach Bryan Featuring Maggie Rogers,-,42,15
99,Rubicon,Peso Pluma,-,63,6

# Question 6)

In [36]:
driver = webdriver.Chrome()
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [37]:
driver.maximize_window()

In [38]:
book = []
author = []
genre = []
publisher = []
sale = []

In [39]:
Book = driver.find_elements(By.XPATH,'//td[@class="left"][2]')
for b in Book:
    book.append(b.text)
    
Author = driver.find_elements(By.XPATH,'//td[@class="left"][3]')
for a in Author:
    author.append(a.text)
    
Genre = driver.find_elements(By.XPATH,'//td[@class="last left"]')
for g in Genre:
    genre.append(g.text)
    
Publisher = driver.find_elements(By.XPATH,'//td[@class="left"][5]')
for p in Publisher:
    publisher.append(p.text)
    
Sale = driver.find_elements(By.XPATH,'//td[@class="left"][4]')
for s in Sale:
    sale.append(s.text)

In [40]:
print(len(book),len(author),len(genre),len(sale),len(publisher))

100 100 100 100 100

In [41]:
df = pd.DataFrame({'BOOK NAME':book,'AUTHOR':author,'PUBLISHER':publisher,'SALES IN VOLUME':sale,'GENRE':genre})
df

,BOOK NAME,AUTHOR,PUBLISHER,SALES IN VOLUME,GENRE
0,"Da Vinci Code,The","Brown, Dan",Transworld,"5,094,805","Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Bloomsbury,"4,475,152",Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Bloomsbury,"4,200,654",Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Bloomsbury,"4,179,479",Children's Fiction
4,Fifty Shades of Grey,"James, E. L.",Random House,"3,758,936",Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert",Random House,"807,311",General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie",Penguin,"794,201",Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",Scholastic Ltd.,"792,187",Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",Orion,"791,507",Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Penguin,"791,095",Food & Drink: General

#  Question 7)

In [17]:
driver = webdriver.Chrome()
driver.get("http://www.imdb.com/list/ls095964455/")

In [18]:
driver.maximize_window()

In [24]:
name = []
year = []
genre = []
run_time = []
ratings = []
votes = []

In [25]:
Name = driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div[3]/div/div[2]/h3/a')
for n in Name:
    name.append(n.text)
    
Year = driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
for y in Year:
    year.append(y.text)
    
Genre = driver.find_elements(By.XPATH,'//span[@class="genre"]')
for g in Genre:
    genre.append(g.text)
    
time = driver.find_elements(By.XPATH,'//span[@class="runtime"]')
for t in time:
    run_time.append(t.text)
    
rating = driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div[3]/div/div[2]/div[1]/div[1]/span[2]')
for r in rating:
    ratings.append(r.text)
    
vote = driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div[3]/div/div[2]/p[4]/span[2]')
for v in vote:
    votes.append(v.text)

In [27]:
print(len(name),len(year),len(genre),len(run_time),len(ratings),len(votes))

100 100 100 100 100 100

In [28]:
df = pd.DataFrame({'Name':name,'Year Span':year,'Run Time':run_time,'Genre':genre,'Ratings':ratings,'Votes':votes})
df

,Name,Year Span,Run Time,Genre,Ratings,Votes
0,Game of Thrones,(2011–2019),57 min,"Action, Adventure, Drama",9.2,"2,193,010"
1,Stranger Things,(2016–2024),51 min,"Drama, Fantasy, Horror",8.7,"1,266,779"
2,The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.1,"1,040,933"
3,13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.5,"305,951"
4,The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"265,023"
...,...,...,...,...,...,...
95,Reign,(2013–2017),42 min,Drama,7.4,"52,423"
96,A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"64,451"
97,Criminal Minds,(2005– ),42 min,"Crime, Drama, Mystery",8.1,"210,093"
98,Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7,"43,681"
99,The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"263,647"

# Question 8)

In [42]:
driver = webdriver.Chrome()
driver.get("https://archive.ics.uci.edu/")

In [43]:
driver.maximize_window()

In [44]:
datasets = driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
datasets.click()

In [46]:
expand = driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]/div[2]/span[2]')
expand.click()

In [54]:
name = []
data_type = []
task = []
attribute_type = []
instances_n = []
attribute_n = []
year = []
url = []

In [55]:
for i in range(10):
    print('scrapping page', i+1)
    
    Name = driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]')
    for n in Name:
        name.append(n.text)
    
    Year = driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]')
    for y in Year:
        year.append(y.text)
    year = [Year.split('/')[-1] for Year in year]
    
    i_n = driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div/div[1]/div[2]/div/div[3]/span')
    for i in i_n:
        instances_n.append(i.text)
    
    a_n = driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div/div[1]/div[2]/div/div[4]/span')
    for a in a_n:
        attribute_n.append(a.text)
    
    URL = driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div/div[1]/div[2]/h2/a')
    for u in URL:
        url.append(u.get_attribute('href'))
    
    a_type = driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]')
    for a in a_type:
        attribute_type.append(a.text)
    

    next_button = driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    next_button.click()
    
    time.sleep(5)

scrapping page 1
scrapping page 2
scrapping page 3
scrapping page 4
scrapping page 5
scrapping page 6
scrapping page 7
scrapping page 8
scrapping page 9
scrapping page 10

In [57]:
print(len(url),len(year),len(instances_n),len(attribute_n),len(attribute_type))

100 100 100 100 100

In [58]:
url

['https://archive.ics.uci.edu/dataset/53/iris',
 'https://archive.ics.uci.edu/dataset/45/heart+disease',
 'https://archive.ics.uci.edu/dataset/2/adult',
 'https://archive.ics.uci.edu/dataset/602/dry+bean+dataset',
 'https://archive.ics.uci.edu/dataset/34/diabetes',
 'https://archive.ics.uci.edu/dataset/109/wine',
 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic',
 'https://archive.ics.uci.edu/dataset/545/rice+cammeo+and+osmancik',
 'https://archive.ics.uci.edu/dataset/19/car+evaluation',
 'https://archive.ics.uci.edu/dataset/73/mushroom',
 'https://archive.ics.uci.edu/dataset/1/abalone',
 'https://archive.ics.uci.edu/dataset/14/breast+cancer',
 'https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data',
 'https://archive.ics.uci.edu/dataset/42/glass+identification',
 'https://archive.ics.uci.edu/dataset/186/wine+quality',
 'https://archive.ics.uci.edu/dataset/20/census+income',
 'https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original',
 'https://archive.ics.uci.edu/dataset/9/auto+mpg',
 'https://archive.ics.uci.edu/dataset/10/automobile',
 'https://archive.ics.uci.edu/dataset/102/thyroid+disease',
 'https://archive.ics.uci.edu/dataset/222/bank+marketing',
 'https://archive.ics.uci.edu/dataset/94/spambase',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/27/credit+approval',
 'https://archive.ics.uci.edu/dataset/111/zoo',
 'https://archive.ics.uci.edu/dataset/60/liver+disorders',
 'https://archive.ics.uci.edu/dataset/62/lung+cancer',
 'https://archive.ics.uci.edu/dataset/320/student+performance',
 'https://archive.ics.uci.edu/dataset/52/ionosphere',
 'https://archive.ics.uci.edu/dataset/59/letter+recognition',
 'https://archive.ics.uci.edu/dataset/51/internet+advertisements',
 'https://archive.ics.uci.edu/dataset/502/online+retail+ii',
 'https://archive.ics.uci.edu/dataset/81/pen+based+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/105/congressional+voting+records',
 'https://archive.ics.uci.edu/dataset/31/covertype',
 'https://archive.ics.uci.edu/dataset/50/image+segmentation',
 'https://archive.ics.uci.edu/dataset/46/hepatitis',
 'https://archive.ics.uci.edu/dataset/352/online+retail',
 'https://archive.ics.uci.edu/dataset/110/yeast',
 'https://archive.ics.uci.edu/dataset/29/computer+hardware',
 'https://archive.ics.uci.edu/dataset/101/tic+tac+toe+endgame',
 'https://archive.ics.uci.edu/dataset/151/connectionist+bench+sonar+mines+vs+rocks',
 'https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients',
 'https://archive.ics.uci.edu/dataset/76/nursery',
 'https://archive.ics.uci.edu/dataset/143/statlog+australian+credit+approval',
 'https://archive.ics.uci.edu/dataset/137/reuters+21578+text+categorization+collection',
 'https://archive.ics.uci.edu/dataset/16/breast+cancer+wisconsin+prognostic',
 'https://archive.ics.uci.edu/dataset/90/soybean+large',
 'https://archive.ics.uci.edu/dataset/5/arrhythmia',
 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention+dataset',
 'https://archive.ics.uci.edu/dataset/12/balance+scale',
 'https://archive.ics.uci.edu/dataset/98/statlog+project',
 'https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite',
 'https://archive.ics.uci.edu/dataset/121/eeg+database',
 'https://archive.ics.uci.edu/dataset/91/soybean+small',
 'https://archive.ics.uci.edu/dataset/148/statlog+shuttle',
 'https://archive.ics.uci.edu/dataset/145/statlog+heart',
 'https://archive.ics.uci.edu/dataset/54/isolet',
 'https://archive.ics.uci.edu/dataset/67/molecular+biology+promoter+gene+sequences',
 'https://archive.ics.uci.edu/dataset/149/statlog+vehicle+silhouettes',
 'https://archive.ics.uci.edu/dataset/240/human+activity+recognition+using+smartphones',
 'https://archive.ics.uci.edu/dataset/107/waveform+database+generator+version+1',
 'https://archive.ics.uci.edu/dataset/39/ecoli',
 'https://archive.ics.uci.edu/dataset/33/dermatology',
 'https://archive.ics.uci.edu/dataset/125/insurance+company+benchmark+coil+2000',
 'https://archive.ics.uci.edu/dataset/154/protein+data',
 'https://archive.ics.uci.edu/dataset/70/monk+s+problems',
 'https://archive.ics.uci.edu/dataset/4/anonymous+microsoft+web+data',
 'https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences',
 'https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption',
 'https://archive.ics.uci.edu/dataset/89/solar+flare',
 'https://archive.ics.uci.edu/dataset/30/contraceptive+method+choice',
 'https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition',
 'https://archive.ics.uci.edu/dataset/132/movie',
 'https://archive.ics.uci.edu/dataset/74/musk+version+1',
 'https://archive.ics.uci.edu/dataset/40/flags',
 'https://archive.ics.uci.edu/dataset/58/lenses',
 'https://archive.ics.uci.edu/dataset/124/cmu+face+images',
 'https://archive.ics.uci.edu/dataset/43/haberman+s+survival',
 'https://archive.ics.uci.edu/dataset/87/servo',
 'https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset',
 'https://archive.ics.uci.edu/dataset/228/sms+spam+collection',
 'https://archive.ics.uci.edu/dataset/130/kdd+cup+1999+data',
 'https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope',
 'https://archive.ics.uci.edu/dataset/95/spect+heart',
 'https://archive.ics.uci.edu/dataset/47/horse+colic',
 'https://archive.ics.uci.edu/dataset/22/chess+king+rook+vs+king+pawn',
 'https://archive.ics.uci.edu/dataset/162/forest+fires',
 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008',
 'https://archive.ics.uci.edu/dataset/117/census+income+kdd',
 'https://archive.ics.uci.edu/dataset/83/primary+tumor',
 'https://archive.ics.uci.edu/dataset/38/echocardiogram',
 'https://archive.ics.uci.edu/dataset/116/us+census+data+1990',
 'https://archive.ics.uci.edu/dataset/72/multiple+features',
 'https://archive.ics.uci.edu/dataset/3/annealing',
 'https://archive.ics.uci.edu/dataset/13/balloons',
 'https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records',
 'https://archive.ics.uci.edu/dataset/25/bach+chorales']

In [59]:
for u in url:
    driver.get(u)
    time.sleep(5)
    
    try:
        Task = driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p')
        task.append(Task.text)
        
    except NoSuchElementException:
        task.append('-')
        
    try:
        dt = driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[1]/p')
        data_type.append(dt.text)
        
    except NoSuchElementException:
        data_type.append('-')

In [60]:
df = pd.DataFrame({'Dataset name':name,' Data type':data_type,'Task':task,'Attribute type':attribute_type,'No. of instances':instances_n,'No. of attribute':attribute_n,'Year':year})
df

,Dataset name,Data type,Task,Attribute type,No. of instances,No. of attribute,Year
0,Iris,Multivariate,Classification,Real,150 Instances,4 Attributes,1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303 Instances,13 Attributes,1988
2,Adult,Multivariate,Classification,"Categorical, Integer",48.84K Instances,14 Attributes,1996
3,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13.61K Instances,16 Attributes,2020
4,Diabetes,"Multivariate, Time-Series",-,"Categorical, Integer",,20 Attributes,A
...,...,...,...,...,...,...,...
95,Multiple Features,Multivariate,Classification,"Integer, Real",2K Instances,649 Attributes,A
96,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798 Instances,38 Attributes,A
97,Balloons,Multivariate,Classification,Categorical,16 Instances,4 Attributes,A
98,Heart failure clinical records,Multivariate,"Classification, Regression, Clustering","Integer, Real",299 Instances,13 Attributes,2020
99,Bach Chorales,"Univariate, Time-Series",-,"Categorical, Integer",100 Instances,6 Attributes,A